package com.lhx.model;

import java.util.Date;

public class Dashboard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.dashboardId
     *
     * @mbggenerated
     */
    private Integer dashboardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.accountId
     *
     * @mbggenerated
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.parentId
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.parentDashboard
     *
     * @mbggenerated
     */
    private Integer parentdashboard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.sourceId
     *
     * @mbggenerated
     */
    private Integer sourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.sourceDashboard
     *
     * @mbggenerated
     */
    private Integer sourcedashboard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.loadMore
     *
     * @mbggenerated
     */
    private String loadmore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.dashboardType
     *
     * @mbggenerated
     */
    private Byte dashboardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.dashboardData
     *
     * @mbggenerated
     */
    private Integer dashboarddata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.dashboardTitle
     *
     * @mbggenerated
     */
    private String dashboardtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.permissionType
     *
     * @mbggenerated
     */
    private Byte permissiontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.dashboardTime
     *
     * @mbggenerated
     */
    private Date dashboardtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.lng
     *
     * @mbggenerated
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.lat
     *
     * @mbggenerated
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.dashboardTag
     *
     * @mbggenerated
     */
    private String dashboardtag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.sourceClient
     *
     * @mbggenerated
     */
    private String sourceclient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.sourceUrl
     *
     * @mbggenerated
     */
    private String sourceurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.dashboardFlag
     *
     * @mbggenerated
     */
    private Boolean dashboardflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.rebolgFlag
     *
     * @mbggenerated
     */
    private Boolean rebolgflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.rebolgLevel
     *
     * @mbggenerated
     */
    private Short rebolglevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.ztFlag
     *
     * @mbggenerated
     */
    private Boolean ztflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.blockFlag
     *
     * @mbggenerated
     */
    private Boolean blockflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.contentTime
     *
     * @mbggenerated
     */
    private Long contenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.ipaddress
     *
     * @mbggenerated
     */
    private String ipaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dashboard_basic.dashboardAbstract
     *
     * @mbggenerated
     */
    private String dashboardabstract;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.dashboardId
     *
     * @return the value of dashboard_basic.dashboardId
     *
     * @mbggenerated
     */
    public Integer getDashboardid() {
        return dashboardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.dashboardId
     *
     * @param dashboardid the value for dashboard_basic.dashboardId
     *
     * @mbggenerated
     */
    public void setDashboardid(Integer dashboardid) {
        this.dashboardid = dashboardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.accountId
     *
     * @return the value of dashboard_basic.accountId
     *
     * @mbggenerated
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.accountId
     *
     * @param accountid the value for dashboard_basic.accountId
     *
     * @mbggenerated
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.parentId
     *
     * @return the value of dashboard_basic.parentId
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.parentId
     *
     * @param parentid the value for dashboard_basic.parentId
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.parentDashboard
     *
     * @return the value of dashboard_basic.parentDashboard
     *
     * @mbggenerated
     */
    public Integer getParentdashboard() {
        return parentdashboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.parentDashboard
     *
     * @param parentdashboard the value for dashboard_basic.parentDashboard
     *
     * @mbggenerated
     */
    public void setParentdashboard(Integer parentdashboard) {
        this.parentdashboard = parentdashboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.sourceId
     *
     * @return the value of dashboard_basic.sourceId
     *
     * @mbggenerated
     */
    public Integer getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.sourceId
     *
     * @param sourceid the value for dashboard_basic.sourceId
     *
     * @mbggenerated
     */
    public void setSourceid(Integer sourceid) {
        this.sourceid = sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.sourceDashboard
     *
     * @return the value of dashboard_basic.sourceDashboard
     *
     * @mbggenerated
     */
    public Integer getSourcedashboard() {
        return sourcedashboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.sourceDashboard
     *
     * @param sourcedashboard the value for dashboard_basic.sourceDashboard
     *
     * @mbggenerated
     */
    public void setSourcedashboard(Integer sourcedashboard) {
        this.sourcedashboard = sourcedashboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.loadMore
     *
     * @return the value of dashboard_basic.loadMore
     *
     * @mbggenerated
     */
    public String getLoadmore() {
        return loadmore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.loadMore
     *
     * @param loadmore the value for dashboard_basic.loadMore
     *
     * @mbggenerated
     */
    public void setLoadmore(String loadmore) {
        this.loadmore = loadmore == null ? null : loadmore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.dashboardType
     *
     * @return the value of dashboard_basic.dashboardType
     *
     * @mbggenerated
     */
    public Byte getDashboardtype() {
        return dashboardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.dashboardType
     *
     * @param dashboardtype the value for dashboard_basic.dashboardType
     *
     * @mbggenerated
     */
    public void setDashboardtype(Byte dashboardtype) {
        this.dashboardtype = dashboardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.dashboardData
     *
     * @return the value of dashboard_basic.dashboardData
     *
     * @mbggenerated
     */
    public Integer getDashboarddata() {
        return dashboarddata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.dashboardData
     *
     * @param dashboarddata the value for dashboard_basic.dashboardData
     *
     * @mbggenerated
     */
    public void setDashboarddata(Integer dashboarddata) {
        this.dashboarddata = dashboarddata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.dashboardTitle
     *
     * @return the value of dashboard_basic.dashboardTitle
     *
     * @mbggenerated
     */
    public String getDashboardtitle() {
        return dashboardtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.dashboardTitle
     *
     * @param dashboardtitle the value for dashboard_basic.dashboardTitle
     *
     * @mbggenerated
     */
    public void setDashboardtitle(String dashboardtitle) {
        this.dashboardtitle = dashboardtitle == null ? null : dashboardtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.permissionType
     *
     * @return the value of dashboard_basic.permissionType
     *
     * @mbggenerated
     */
    public Byte getPermissiontype() {
        return permissiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.permissionType
     *
     * @param permissiontype the value for dashboard_basic.permissionType
     *
     * @mbggenerated
     */
    public void setPermissiontype(Byte permissiontype) {
        this.permissiontype = permissiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.dashboardTime
     *
     * @return the value of dashboard_basic.dashboardTime
     *
     * @mbggenerated
     */
    public Date getDashboardtime() {
        return dashboardtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.dashboardTime
     *
     * @param dashboardtime the value for dashboard_basic.dashboardTime
     *
     * @mbggenerated
     */
    public void setDashboardtime(Date dashboardtime) {
        this.dashboardtime = dashboardtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.lng
     *
     * @return the value of dashboard_basic.lng
     *
     * @mbggenerated
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.lng
     *
     * @param lng the value for dashboard_basic.lng
     *
     * @mbggenerated
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.lat
     *
     * @return the value of dashboard_basic.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.lat
     *
     * @param lat the value for dashboard_basic.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.dashboardTag
     *
     * @return the value of dashboard_basic.dashboardTag
     *
     * @mbggenerated
     */
    public String getDashboardtag() {
        return dashboardtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.dashboardTag
     *
     * @param dashboardtag the value for dashboard_basic.dashboardTag
     *
     * @mbggenerated
     */
    public void setDashboardtag(String dashboardtag) {
        this.dashboardtag = dashboardtag == null ? null : dashboardtag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.sourceClient
     *
     * @return the value of dashboard_basic.sourceClient
     *
     * @mbggenerated
     */
    public String getSourceclient() {
        return sourceclient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.sourceClient
     *
     * @param sourceclient the value for dashboard_basic.sourceClient
     *
     * @mbggenerated
     */
    public void setSourceclient(String sourceclient) {
        this.sourceclient = sourceclient == null ? null : sourceclient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.sourceUrl
     *
     * @return the value of dashboard_basic.sourceUrl
     *
     * @mbggenerated
     */
    public String getSourceurl() {
        return sourceurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.sourceUrl
     *
     * @param sourceurl the value for dashboard_basic.sourceUrl
     *
     * @mbggenerated
     */
    public void setSourceurl(String sourceurl) {
        this.sourceurl = sourceurl == null ? null : sourceurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.dashboardFlag
     *
     * @return the value of dashboard_basic.dashboardFlag
     *
     * @mbggenerated
     */
    public Boolean getDashboardflag() {
        return dashboardflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.dashboardFlag
     *
     * @param dashboardflag the value for dashboard_basic.dashboardFlag
     *
     * @mbggenerated
     */
    public void setDashboardflag(Boolean dashboardflag) {
        this.dashboardflag = dashboardflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.rebolgFlag
     *
     * @return the value of dashboard_basic.rebolgFlag
     *
     * @mbggenerated
     */
    public Boolean getRebolgflag() {
        return rebolgflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.rebolgFlag
     *
     * @param rebolgflag the value for dashboard_basic.rebolgFlag
     *
     * @mbggenerated
     */
    public void setRebolgflag(Boolean rebolgflag) {
        this.rebolgflag = rebolgflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.rebolgLevel
     *
     * @return the value of dashboard_basic.rebolgLevel
     *
     * @mbggenerated
     */
    public Short getRebolglevel() {
        return rebolglevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.rebolgLevel
     *
     * @param rebolglevel the value for dashboard_basic.rebolgLevel
     *
     * @mbggenerated
     */
    public void setRebolglevel(Short rebolglevel) {
        this.rebolglevel = rebolglevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.ztFlag
     *
     * @return the value of dashboard_basic.ztFlag
     *
     * @mbggenerated
     */
    public Boolean getZtflag() {
        return ztflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.ztFlag
     *
     * @param ztflag the value for dashboard_basic.ztFlag
     *
     * @mbggenerated
     */
    public void setZtflag(Boolean ztflag) {
        this.ztflag = ztflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.blockFlag
     *
     * @return the value of dashboard_basic.blockFlag
     *
     * @mbggenerated
     */
    public Boolean getBlockflag() {
        return blockflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.blockFlag
     *
     * @param blockflag the value for dashboard_basic.blockFlag
     *
     * @mbggenerated
     */
    public void setBlockflag(Boolean blockflag) {
        this.blockflag = blockflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.contentTime
     *
     * @return the value of dashboard_basic.contentTime
     *
     * @mbggenerated
     */
    public Long getContenttime() {
        return contenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.contentTime
     *
     * @param contenttime the value for dashboard_basic.contentTime
     *
     * @mbggenerated
     */
    public void setContenttime(Long contenttime) {
        this.contenttime = contenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.ipaddress
     *
     * @return the value of dashboard_basic.ipaddress
     *
     * @mbggenerated
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.ipaddress
     *
     * @param ipaddress the value for dashboard_basic.ipaddress
     *
     * @mbggenerated
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress == null ? null : ipaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dashboard_basic.dashboardAbstract
     *
     * @return the value of dashboard_basic.dashboardAbstract
     *
     * @mbggenerated
     */
    public String getDashboardabstract() {
        return dashboardabstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dashboard_basic.dashboardAbstract
     *
     * @param dashboardabstract the value for dashboard_basic.dashboardAbstract
     *
     * @mbggenerated
     */
    public void setDashboardabstract(String dashboardabstract) {
        this.dashboardabstract = dashboardabstract == null ? null : dashboardabstract.trim();
    }
}